name: Deploy React Application

on:
  push:
    branches: [ feature/deploy ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: npm install, build
        run: |
          cd demo
          npm install
          npm run build
      - name: deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./build          